### ISSUE TITLE
unexpected token error

### ISSUE THREAD

**Issue by Mouvedia** [patrickmarabeas/ng-FitText.js#12]
"[$parse:syntax] Syntax Error: Token '{' is an unexpected token at column 21 of the expression [{fontSize:fontSize} {fontSize:fontSize}] starting at [{fontSize:fontSize}]"

I don't have time to investigate right now but here's the piece of code that produces that error

```
<h5 data-fittext>{{object.property}}</h5>
```

which is inside a directive and a ng repeat.

**Comment by thanuzz** [comment]
Encountering the same error as mentioned above. When I remove the fittext directives the error does not occur. The Fittext directive is situated within multiple other directives (md-content/md-card /md-card-header, using the Angular Material framework)

```
VM21814:27TypeError: Cannot read property 'exp' of undefined
    at watchFnToHumanReadableString (<anonymous>:703:19)
    at Scope.$delegate.__proto__.$watch (<anonymous>:735:28)
    at Object.link (http://localhost:3000/js/scripts.js:80084:944)
    at http://localhost:3000/js/scripts.js:2815:18
    at invokeLinkFn (http://localhost:3000/js/scripts.js:11306:9)
    at nodeLinkFn (http://localhost:3000/js/scripts.js:10705:11)
    at compositeLinkFn (http://localhost:3000/js/scripts.js:10008:13)
    at nodeLinkFn (http://localhost:3000/js/scripts.js:10700:24)
    at compositeLinkFn (http://localhost:3000/js/scripts.js:10008:13)
    at compositeLinkFn (http://localhost:3000/js/scripts.js:10011:13) <h2 class="md-title has-label ng-scope ng-binding" data-fittext="" data-fittext-max="inherit" ng-class="{ 'has-label': product.labelText }">
```

My (simplified) code: 
```
    <md-content>
        <div ng-repeat="product in productList.products" ng-click="productList.goToDetail(product)">
            <md-card>
                <md-card-header>
                    <md-card-header-text layout-align="center" layout="row">
                        <h2 data-fittext="" data-fittext-max="inherit" ng-class="{ 'has-label': product.labelText }">{{ ::product.name }}</h2>
                    </md-card-header-text>
                </md-card-header>
            </md-card>
        </div>
    </md-content>
```

Couldn't find a working solution in the posts above. 
Any help would be appreciated! 
Thanks in advance.

**Comment by patrickmarabeas** [comment]
@thanuzz any chance you can demo the issue in a codepen or similar?
